---
name: Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

concurrency:
  group: lint-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-eslint:
    name: 👕 ESLint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm lint
  lint-markdown-links:
    uses: timmo001/workflows/.github/workflows/lint-markdown-links.yml@master
  lint-markdownlint:
    uses: timmo001/workflows/.github/workflows/lint-markdownlint.yml@master
  lint-yamllint:
    uses: timmo001/workflows/.github/workflows/lint-yamllint.yml@master
